apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
spec:
  selector:
    matchLabels:
      run: poi
  replicas: 1
  template:
    metadata:
      labels:
        run: poi
    spec:
      containers:
      - name: poi
        image: registryqft0511.azurecr.io/tripinsights/poi:1.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: keyvault
          mountPath: /secrets
          readOnly: true
      volumes:
      - name: keyvault
        flexVolume:
          driver: "azure/kv"
          secretRef:
            name: kvcredentials              # [OPTIONAL] not required if using Pod Identity
          options:
            keyvaultname: "team14KeyVault"               # the name of the KeyVault
            keyvaultobjectnames: sql-dbname;sql-password;sql-server;sql-username    # list of KeyVault object names (semi-colon separated)
            keyvaultobjecttypes: secret;secret;secret;secret  # list of KeyVault object types: secret, key or cert (semi-colon separated)
            keyvaultobjectaliases: SQL_DBNAME;SQL_PASSWORD;SQL_SERVER;SQL_USER
            resourcegroup: "teamResources"              # [REQUIRED FOR < v0.0.14] the resource group of the KeyVault
            subscriptionid: "c0b0ad00-c6a9-40a1-adaf-7d290c84721c"             # [REQUIRED FOR < v0.0.14] the subscription ID of the KeyVault
            tenantid: "13823b52-457a-4034-b4aa-4b5666eb72c1"                   # the tenant ID of the KeyVault