apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
spec:
  selector:
    matchLabels:
      run: tripviewer
  replicas: 1
  template:
    metadata:
      labels:
        run: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registryqft0511.azurecr.io/tripinsights/tripviewer:1.0
        ports:
        - containerPort: 80
        env:
        - name: USERPROFILE_API_ENDPOINT
          value: http://userprofile.default.svc.cluster.local
        - name: TRIPS_API_ENDPOINT
          value: http://trips.default.svc.cluster.local