apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
spec:
  selector:
    matchLabels:
      run: trips
  replicas: 1
  template:
    metadata:
      labels:
        run: trips
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: db-sqlserver-secrets
      containers:
      - name: trips
        image: registryqft0511.azurecr.io/tripinsights/trips:1.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/secrets"
        env:
        - name: OPENAPI_DOCS_URI
          value: "10.0.26.11:80"
        - name: DEBUG_LOGGING
          value: "NO"
