apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
spec:
  selector:
    matchLabels:
      run: trips
  replicas: 1
  template:
    metadata:
      labels:
        run: trips
    spec:
      containers:
      - name: trips
        image: registryqft0511.azurecr.io/tripinsights/trips:1.0
        ports:
        - containerPort: 80
        env:
        - name: DSQL_USER	Yes	ENV or File	sqladmin	The username for the SQL Server database.
          value: "sqladminqFt0511"
        - name: DSQL_PASSWORD
          value: "nG4vq6Pc4"
        - name: DSQL_SERVER
          value: "sqlserverqft0511.database.windows.net"
        - name: DSQL_DBNAME
          value: "mydrivingDB"
        - name: DOPENAPI_DOCS_URI
          value: "10.0.26.11:80"
        - name: DDEBUG_LOGGING
          value: NO
