apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
spec:
  selector:
    matchLabels:
      run: tripviewer
  replicas: 2
  template:
    metadata:
      labels:
        run: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registryqft0511.azurecr.io/tripinsights/tripviewer:1.0
        ports:
        - containerPort: 80
