apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
spec:
  selector:
    matchLabels:
      run: userprofile
  replicas: 1
  template:
    metadata:
      labels:
        run: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryqft0511.azurecr.io/tripinsights/userprofile:1.0
        ports:
        - containerPort: 80
        env:
        - name: SQL_SERVER
          value: "sqlserverqft0511.database.windows.net"
        - name: SQL_USER
          value: "sqladminqFt0511"
        - name: SQL_PASSWORD
          value: "nG4vq6Pc4"
        - name: SQL_DBNAME
          value: "mydrivingDB"
