apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
spec:
  selector:
    matchLabels:
      run: userprofile
  replicas: 1
  template:
    metadata:
      labels:
        run: userprofile
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: db-sqlserver-secrets
      containers:
      - name: userprofile
        image: registryqft0511.azurecr.io/tripinsights/userprofile:1.0
        volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/secrets"
        ports:
        - containerPort: 80
