apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
spec:
  selector:
    matchLabels:
      run: userprofile
  replicas: 1
  template:
    metadata:
      labels:
        run: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryqft0511.azurecr.io/tripinsights/userprofile:1.0
        ports:
        - containerPort:80
